version: '3'

services:
    traefik:
        image: traefik:v1.7.16
        networks:
            - webgateway
        ports:
            - "8000:8000"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/anas/logs:/home/anas/logs
            - ./traefik.toml:/traefik.toml

networks:
    webgateway:
        driver: bridge
