defaultEntryPoints = ["http"]
logLevel = "DEBUG"

[api]
address = ":8081"

[entryPoints]
    [entryPoints.http]
    address = ":8080"

[retry]
attempts = 3
maxMem = 3

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "localhost"
watch = true
exposedbydefault = false