defaultEntryPoints = ["http"]
logLevel = "DEBUG"

[api]
address = ":8080"

[entryPoints]
    [entryPoints.http]
    address = ":8000"

[retry]
attempts = 3
maxMem = 3

[accessLog]
  filePath = "/home/anas/access.log"
  format = "json"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "localhost"
watch = true
exposedbydefault = false